const staffApi = [
  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Zongo",
    last_name: "Hasani",
    email: "Hasani@yahoo.com",
    phone: "0244740703",
    position: "Teacher",
    subject: "Science",
    location: "Unknown",
    close_relative: "Mr Andah Hilama",
    close_relative_phone: "0246582000",
    grade: "8",
    adminAccess: "true",
  },

  {
    first_name: "Kraig",
    last_name: "Hasford",
    email: "K.H@yahoo.com",
    phone: "0579740703",
    position: "Teacher",
    subject: "Physical Education",
    location: "Unknown",
    close_relative: "Mr Fusani HasHash",
    close_relative_phone: "02312322",
    grade: "4",
    adminAccess: "true",
  },

  {
    first_name: "Kwame",
    last_name: "Ofosu",
    email: "KO@yahoo.com",
    phone: "12003223",
    position: "Teacher",
    subject: "Art",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Usif",
    last_name: "Zamani",
    email: "UZI@yahoo.com",
    phone: "83789232",
    position: "Teacher",
    subject: "English",
    location: "Unknown",
    close_relative: "Mr Fosuwaa",
    close_relative_phone: "07332232",
    grade: "12",
    adminAccess: "true",
  },

  {
    first_name: "Yami",
    last_name: "Hank",
    email: "Hany@yahoo.com",
    phone: "32321232",
    position: "Teacher",
    subject: "Social Studies",
    location: "Unknown",
    close_relative: "Mr kilwak Mahuma",
    close_relative_phone: "88888288",
    grade: "9",
    adminAccess: "false",
  },

  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },

  {
    first_name: "Emmanuel",
    last_name: "Rajesh",
    email: "emma@yahoo.com",
    phone: "0546740703",
    position: "Teacher",
    subject: "Mathematics",
    location: "Unknown",
    close_relative: "Mr Rupesh Mahuma",
    close_relative_phone: "0246582765",
    grade: "2",
    adminAccess: "false",
  },
];

export default staffApi;
